spring:
  application:
    name: structure
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    properties:
      hibernate:
        default_schema: financial_lab_structure
  datasource:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    driver-class-name: org.postgresql.Driver
    url: ${JDBC_URL:jdbc:postgresql://localhost:5432/financial_lab_structure}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:root}

aws:
  region: ${AWS_REGION}
  s3:
    example-documents: ${S3_EXAMPLE_DOCUMENTS}
    path-example-documents: ${S3_PATH_EXAMPLE_DOCUMENTS}

feign:
  client:
    config:
      default:
        logger-level: warn
  okhttp:
    enabled: true

server:
  port: ${SERVER_PORT:8080}
  ssl:
    enabled: ${ENABLE_SSL:false}
    client-auth: none
    key-store: ${SSL_CERT_PATH}
    key-store-password: ${SSL_CERT_PASS}
    key-store-type: ${SSL_STORE_TYPE}
    key-alias: ${SSL_CERT_ALIAS}

management:
  server:
    port: ${PROMETHEUS_PORT:9090}
  endpoints:
    web:
      exposure:
        include:
          - prometheus
          - health
  metrics:
    export:
      prometheus:
        enabled: true