spring.config.import: "aws-secretsmanager:finance-control/database"

spring:
  application:
    name: financecontrol
  jpa:
    properties:
      hibernate:
        default_schema: finance_db
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${JDBC_URL:jdbc:postgresql://localhost:5432/finance_db}
    username: ${username}
    password: ${password}

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:root}

spring.cloud:
  aws:
    region:
      static: ${AWS_REGION:us-east-1}
    credentials:
      access-key: ${AWS_ACCESS_KEY:local_access}
      secret-key: ${AWS_SECRET_KEY:local_secret}
    endpoint: ${LOCALSTACK_URL:http://localhost:5566}

server:
  port: ${SERVER_PORT:8080}

management:
  server:
    port: ${PROMETHEUS_PORT:9091}
  endpoints:
    web:
      exposure:
        include:
          - prometheus
          - health
  metrics:
    export:
      prometheus:
        enabled: true

app:
  simulate-consumer-failure: false
