spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisReactiveAutoConfiguration

spring.cloud:
  aws:
    region:
      static: us-east-1
    credentials:
      access-key: test
      secret-key: test
    sqs:
      enabled: false
    secretsmanager:
      enabled: false

management:
  health:
    redis:
      enabled: false
